name: NoteBlockRecorder
version: ${project.version}
main: org.tanberg.noteblockrecorder.NoteBlockRecorder
api-version: 1.16
authors: [ LorgeN ]

commands:
  record:
    description: Start/stop recording note block events
    permission: noteblockrecorder.record
  play:
    description: Start/stop playback of a recorded song
    permission: noteblockrecorder.play